### ISSUE TITLE
rust-analyzer newly confused by endpoint macro

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/dropshot#134]
Recently, the Rust Analyzer folks enabled (deeper?) processing of proc attribute macros, in: rust-analyzer/rust-analyzer#10366.

It seems that as of that commit, code completion inside endpoint functions (those wrapped by `#[endpoint]`) is a bit flaky.  It will sometimes work once or twice, but then can eventually get confused and stops working altogether.  This state seems to be sticky until you restart RA.

While I am not yet convinced RA is doing entirely the right thing here, it has been suggested in rust-analyzer/rust-analyzer#10498 that:

> The problem is likely that the proc macro emits an error when the function is syntactically invalid. (What error message does rustc emit when faced with this incomplete code?) In that case, probably your only options are to either report this to the proc macro authors and wait for them to fix it, or to disable attribute macro expansion again.

Indeed, `endpoint` _does_ emit an error when the function body is syntactically invalid -- but I'm not really sure what we should do instead?  Should we be doing our best to construct what will be an invalid token stream and passing that back without error, unless the stream is so invalid that it is unrecognisable?

**Comment by flodiebold** [comment]
I started making an [example](https://github.com/flodiebold/proc-macro-levels) with various proc macros that parse input in different ways. Turns out it's [not very complicated](https://github.com/flodiebold/proc-macro-levels/blob/0757ffee9fe2495a5c836fe6a617fda7de3ae265/macros/src/lib.rs#L38-L75) to make something that parses the function signature, but leaves the body as a token stream, and this makes completion work as expected in the body. Dealing perfectly with the signature would be a bit harder.
