### ISSUE TITLE
Registration of endpoint using nested type with same name causes infinite loop

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/dropshot#150]
I have a repro case here: https://github.com/oxidecomputer/dropshot/pull/149/commits/792932d9dc5bdb6e7f913af0180a29c2533150df

TL;DR:
- When registering an endpoint with a path parameter...
- ... where that path parameter contains multiple structs of the same name (this is common for the "newtype pattern", where the name of a structure only differs by module)...
- ... Registration of the endpoint ends up making a call to `type_resolve`, which [loops forever](https://github.com/oxidecomputer/dropshot/blob/492c12caed4c09a3f9a49542bc197119858400fd/dropshot/src/type_util.rs#L122-L148).

**Comment by ahl** [comment]
It looks like the JSON Schema generated is cyclic:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Params",
  "type": "object",
  "required": [
    "thing"
  ],
  "properties": {
    "thing": {
      "$ref": "#/definitions/TheThing"
    }
  },
  "definitions": {
    "TheThing": {
      "$ref": "#/definitions/TheThing"
    }
  }
}
```

Note that `TheThing` is defined to be a reference to... `TheThing`

1. (obviously) this is a bug (perhaps in `schemars`
2. I'm not completely sure what the best handling of this is, but at a minimum it should hard fail rather than spin
3. A workaround is to use #[serde(transparent)] or #[schemars(transparent)]

This removes the layer of indirection and therefore the infinite recursion:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Params",
  "type": "object",
  "required": [
    "thing"
  ],
  "properties": {
    "thing": {
      "$ref": "#/definitions/TheThing"
    }
  },
  "definitions": {
    "TheThing": {
      "type": "string"
    }
  }
}
```

Another workaround is to use #[schemars/serde(rename = "...")]

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Params",
  "type": "object",
  "required": [
    "thing"
  ],
  "properties": {
    "thing": {
      "$ref": "#/definitions/TheThingKludge"
    }
  },
  "definitions": {
    "TheThing": {
      "type": "string"
    },
    "TheThingKludge": {
      "$ref": "#/definitions/TheThing"
    }
  }
}
```
