### ISSUE TITLE
support for HEAD method

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/dropshot#348]
It would be good to allow endpoints to support the HEAD HTTP method in addition to the existing GET, et al.

**Comment by davepacheco** [comment]
We definitely should do this.

Also, it'd be nice if there were an option to implement some kind of support without having to implement it entirely yourself.  I wonder if we could run the `GET` handler and throw away the response (and tweak whatever response headers need to change)?  Maybe give you a flag you can check to see if it's `GET` or `HEAD` so that if you want to avoid some work, you could?

**Comment by jclulow** [comment]
This was fixed in #755.
