### ISSUE TITLE
context object could be simpler with a derive macro

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/dropshot#38]
I have a pretty simple context object:

```rust
struct Context {
    db: db::Database,
    sig: WaitSignal,
}

impl Context {
    fn from_private(ctx: Arc<dyn Any + Send + Sync + 'static>)
        -> Arc<Context>
    {
        ctx.downcast::<Context>().expect("context downcast")
    }

    fn from_request(rqctx: &Arc<RequestContext>)
        -> Arc<Context>
    {
        Self::from_private(Arc::clone(&rqctx.server.private))
    }
}
```

I then grab this in handlers thus:

```rust
#[endpoint {
    method = GET,
    path = "/gusty/winds/may/exist",
}]
async fn gusty_winds_check(
    rqctx: Arc<RequestContext>,
) -> std::result::Result<HttpResponseOk<GustyWinds>, HttpError> {
    let c = Context::from_request(&rqctx);
    ...
```

I think it is fine to require the `Context::from_request()` call here, but I wonder if we couldn't provide a derive macro to avoid the need to copy paste the `impl Context` that does the conversion.

One could imagine a `From<&Arc<RequestContext>` that you'd get thus:

```rust
#[derive(DropshotContext)]
struct Context {
    blah: String,
};

fn handler(rqctx: Arc<RequestContext>) -> Result<()> {
    let c: Context = rqctx.into();
```

If `From` doesn't work for some reason I am missing, it'd also be fine for `DropshotContext` to just have a `from_request()` method that you'd call the same way as in my original example.

**Comment by davepacheco** [comment]
This is a good idea.  I'd like to try to structure it so that you only have to get the destination type correct in one place (i.e., the wrapper function that we provide for you, or using `into()`).  More on this below.

As you said, the pattern I used in oxide-api-prototype is what you've got there.  I think it's a reasonable tradeoff: by having the consumer provide a wrapper function that does the downcast to the correct type, you don't _quite_ have compile-time checking that the correct type was provided, but there's only one place the type could be wrong.  In practice, because I expect most Dropshot consumers will only use 1 or 2 possible context types, this seems very unlikely to go wrong at runtime.  And if it does, it'll very likely happen on every single request to an endpoint, so basic test coverage should catch it.

Your suggestion to provide a `derive` macro would let us define this function for consumers with as little boilerplate as possible for them.  I think it would have the same tradeoff: you could use it incorrectly, and it would panic at runtime, but this seems unlikely to be a problem in practice.

For background: Actix-web provides an API here that feels like it's more statically type-checked, but can still fail at runtime when misused.  It uses a `Data` extractor similar to the `Query` and `TypedBody` ones that we provide, where the consumer-provided type is given by a type parameter.  I found this interface pretty confusing to use and I ran into cases where misusing it caused runtime failures rather than build-time ones, so I'm not sure it's much better.

Another (bad) option is to just provide a generic function that will cast the private context to whatever type parameter you provide.  This could return a `Result` for consumers that wanted to handle it, but what sort of HttpError would you produce for this?  I guess it could be a 500, but really this feels like a programmer error.  So if the function panics instead if given the wrong type, it's very similar to what we've done, except that the caller has to get the type right at every single call site instead of just in one place.

**Comment by jclulow** [comment]
I think this is obviated by the subsequent restructuring of the context and request information accessors.  You can now just chuck whatever object you have in there and get a reference pretty easily.
