### ISSUE TITLE
allow exclusion of non-API artefacts from the specification

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/dropshot#40]
In the case that a server presents both an API and some other artefacts (e.g., a descriptive or interactive set of HTML pages, images, etc) it would be good to be able to omit those handlers from any API specification that is produced.

**Comment by davepacheco** [comment]
A couple of ideas we discussed:

- Allowing a single Dropshot server to serve multiple `ApiDescription`s (possibly using a consolidated router, so that they can't overlap in the namespace).  I like this because it lets us put other configuration here (e.g., #39)
- adding a "hide_from_spec" boolean to the `endpoint` macro
- using a different macro for something like this

**Comment by jclulow** [comment]
I could see both separate `ApiDescription`s and a `no_spec` boolean being useful at different times.  For example, if we use different `ApiDescription` objects for two different API versions each with a specification -- but both of them have some subset of endpoints we don't wish to include in the document for some reason.

**Comment by jclulow** [comment]
I believe this is covered by the addition of `unpublished = true` in the **endpoint** macro.
